name: build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install pywebview pyinstaller
      - run: pyinstaller --noconfirm --clean --onedir --windowed --name "WUWA Tracker" --icon wuwa.ico --version-file version.txt --exclude-module tkinter --add-data "wuwa-tracker-en.html;." --add-data "wuwa.ico;." wuwa_app.py
      - run: choco install innosetup -y --no-progress
      - run: '& "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss'
      - uses: actions/upload-artifact@v4
        id: upload
        with:
          name: WUWA-Tracker-Setup
          path: Output/WUWA-Tracker-Setup.exe
